# AF-ClaSeq Pipeline Configuration

general:
  # Required paths and identifiers
  source_a3m: "/fs/ess/PAA0203/xing244/AF_ClaSeq/results/CALM_BOVIN/DeepMSA2_local/dMSA_qMSA_combine.a3m"
  default_pdb: "/fs/ess/PAA0203/xing244/AF_ClaSeq/results/CALM_BOVIN/default/CALM_BOVIN_P62157_unrelaxed_rank_001_alphafold2_ptm_model_4_seed_000.pdb"
  base_dir: "/fs/ess/PAA0203/xing244/AF_ClaSeq/results/CALM_BOVIN/run3"
  config_file: "/fs/ess/PAA0203/xing244/AF_ClaSeq/results/CALM_BOVIN/configs/config_1CDL_1CLL_tmscore.json"
  protein_name: "CALM_BOVIN"
  
  # General parameters
  coverage_threshold: 0.8
  num_models: 1
  random_seed: 42
  num_bins: 50  # Updated to match default in config.py
  plot_initial_color: "#87CEEB"
  plot_end_color: "#87CEEB"

slurm:
  conda_env_path: "/fs/ess/PAA0203/xing244/.conda/envs/colabfold"
  slurm_account: "PAA0203"
  slurm_output: "/dev/null"
  slurm_error: "/dev/null"
  slurm_nodes: 1
  slurm_gpus_per_task: 1
  slurm_tasks: 1
  slurm_cpus_per_task: 4
  slurm_time: "04:00:00"
  slurm_partition: "nextgen"
  max_workers: 200

pipeline_control:
  stages:

    # - "01_ANALYSIS"
    # - "02_RUN"
    # - "02_PLOT"  # Note: This should be "02_ANALYSIS" to match default in config.py
    # - "03"
    # - "04"
    - "05"  # Added stage 05 for pure sequence plotting
  check_interval: 60

iterative_shuffling:
  iter_shuf_input_a3m: "/fs/ess/PAA0203/xing244/AF_Vote/results/CALM_BOVIN/DeepMSA2_local/dMSA_qMSA_combine.a3m"
  num_iterations: 2
  num_shuffles: 10
  seq_num_per_shuffle: 16
  plddt_threshold: 75
  quantile: 0.2
  resume_from_iter: null
  iter_shuf_plot_num_cols: 5
  iter_shuf_plot_x_min: 0
  iter_shuf_plot_x_max: 20
  iter_shuf_plot_y_min: 0.8
  iter_shuf_plot_y_max: 10000
  iter_shuf_plot_xticks: null
  iter_shuf_plot_bin_step: 1
  iter_shuf_combine_threshold: 0.7

m_fold_sampling:
  m_fold_samp_input_a3m: "/fs/ess/PAA0203/xing244/AF_ClaSeq/results/CALM_BOVIN/run3/01_iterative_shuffling/analysis/a3m_combine/gathered_seq_after_iter_shuffling-test.a3m"
  m_fold_group_size: 10
  m_fold_random_select: null
  m_fold_plddt_threshold: 0
  m_fold_initial_color: "#87CEEB"
  m_fold_end_color: "#87CEEB"
  m_fold_log_scale: false
  m_fold_n_plot_bins: 50
  m_fold_gradient_ascending: false
  m_fold_linear_gradient: false
  m_fold_figsize: [10, 5]
  m_fold_show_bin_lines: True
  m_fold_count_min: 0
  m_fold_count_max: 50
  m_fold_metric1_min: 0.5
  m_fold_metric1_max: 1.0
  m_fold_metric2_min: 0.5
  m_fold_metric2_max: 1.0
  m_fold_metric1_ticks: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  m_fold_metric2_ticks: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

sequence_voting:
  vote_threshold: 0.0
  vote_min_value: 0.5
  vote_max_value: 1.0
  vote_figsize: [10, 5]
  vote_y_min: 0.8
  vote_y_max: 10000
  vote_x_ticks: [1,10,20,30,40,50]
  vote_hierarchical_sampling: false
  use_focused_bins: True
  
recompile_predict:
  bin_numbers_1: 10
  bin_numbers_2: 1
  combine_bins: false
  metric_name_1: "1CDL_tmscore"
  metric_name_2: "1CLL_tmscore"
  prediction_num_model: 5
  prediction_num_seed: 1
  
pure_sequence_plotting:
  plddt_threshold: 0
  figsize: [15, 7]
  dpi: 600
  metric1_min: 0.5
  metric1_max: 1.0
  metric2_min: 0.5
  metric2_max: 1.0
  metric1_ticks: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  metric2_ticks: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  max_workers: 8