# AF-ClaSeq Pipeline Configuration

general:
  # Required paths and identifiers
  source_a3m: "KaiB_example_msa_input.a3m"
  default_pdb: "default/KaiB_example_msa_input_unrelaxed_rank_001_alphafold2_ptm_model_3_seed_000.pdb"
  base_dir: "run"
  config_file: "configs/config_2qke_5jyt_tmscore.json"
  protein_name: "KaiB"
  
  # General parameters
  coverage_threshold: 0.8
  num_models: 1
  random_seed: 42
  num_bins: 30  # Updated to match default in config.py
  plot_initial_color: "#b985ba"
  plot_end_color: "#b985ba"

slurm:
  conda_env_path: "/fs/ess/PAA0203/xing244/.conda/envs/colabfold"
  slurm_account: "PAA0203"
  slurm_output: "/dev/null"
  slurm_error: "/dev/null"
  slurm_nodes: 1
  slurm_gpus_per_task: 1
  slurm_tasks: 1
  slurm_cpus_per_task: 4
  slurm_time: "04:00:00"
  slurm_partition: "nextgen"
  max_workers: 200

pipeline_control:
  stages:
    # - "01_ITER_SHUF_RUN"
    # - "01_ITER_SHUF_ANALYSIS"
    # - "02_M_FOLD_SAMPLING_RUN"
    - "02_M_FOLD_SAMPLING_PLOT"
    # - "03_VOTING_RUN"
    # - "04_RECOMPILE_PREDICT_RUN"
    # - "05_PURE_SEQ_PLOT_RUN"
  check_interval: 60

iterative_shuffling:
  iter_shuf_input_a3m: "KaiB_example_msa_input.a3m"
  num_iterations: 2
  num_shuffles: 10
  seq_num_per_shuffle: 16
  plddt_threshold: 75
  quantile: 0.2
  enrich_filter_criteria : ["2qke_tmscore"]
  resume_from_iter: null
  iter_shuf_plot_num_cols: 5
  iter_shuf_plot_x_min: 0
  iter_shuf_plot_x_max: 20
  iter_shuf_plot_y_min: 0.8
  iter_shuf_plot_y_max: 10000
  iter_shuf_plot_xticks: null
  iter_shuf_plot_bin_step: 1
  iter_shuf_combine_threshold: 0.7

m_fold_sampling:
  m_fold_samp_input_a3m: "KaiB_example_msa_input.a3m"
  m_fold_group_size: 12
  m_fold_random_select: 120
  m_fold_plddt_threshold: 0
  m_fold_initial_color: "#b985ba"
  m_fold_end_color: "#b985ba"
  m_fold_log_scale: False
  m_fold_n_plot_bins: 30
  m_fold_gradient_ascending: false
  m_fold_linear_gradient: false
  m_fold_figsize: [10, 5]
  m_fold_show_bin_lines: True
  m_fold_count_min: 0
  m_fold_count_max: 40
  m_fold_metric1_min: 0.4
  m_fold_metric1_max: 1.0
  m_fold_metric2_min: 0.4
  m_fold_metric2_max: 1.0
  m_fold_metric1_ticks: [0.4, 0.6, 0.8, 1.0]
  m_fold_metric2_ticks: [0.4, 0.6, 0.8, 1.0]

sequence_voting:
  vote_threshold: 0.0
  vote_min_value: 0.4
  vote_max_value: 1.0
  vote_figsize: [10, 5]
  vote_y_min: 0.8
  vote_y_max: 1000
  vote_x_ticks: [1,10,20,30]
  vote_hierarchical_sampling: false
  use_focused_bins: True
  
recompile_predict:
  bin_numbers_1: [23,26]
  bin_numbers_2: [19,20]
  combine_bins: false
  metric_name_1: "2qke_tmscore"
  metric_name_2: "5jyt_tmscore"
  prediction_num_model: 5
  prediction_num_seed: 8
  
pure_sequence_plotting:
  plddt_threshold: 0
  figsize: [15, 7]
  dpi: 600
  metric1_min: 0.4
  metric1_max: 1.0
  metric2_min: 0.4
  metric2_max: 1.0
  metric1_ticks: [0.4, 0.6, 0.8, 1.0]
  metric2_ticks: [0.4, 0.6, 0.8, 1.0]
  max_workers: 8