"""UMAP projection, grid binning, and diagnostic scatter plots."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd

from af_claseq.utils.logging_utils import get_logger
from af_claseq.utils.exceptions import WorkflowError

from .config import UmapVotingConfig

logger = get_logger("umap_voting.projector")


def embedding_sha256(npz_path: str | Path) -> str:
    """Order-independent hash: sort rows before hashing."""
    data = np.load(npz_path, allow_pickle=True)
    mu = data["mu"]
    sorted_mu = mu[np.lexsort(mu.T)]
    return hashlib.sha256(sorted_mu.tobytes()).hexdigest()


class Projector:
    def __init__(self, config: UmapVotingConfig):
        self.cfg = config
        self.umap_dir = config.get_umap_dir()
        self.umap_dir.mkdir(parents=True, exist_ok=True)

    def fit(self, refit: bool = False) -> pd.DataFrame:
        """Fit or reload UMAP and return umap_coords DataFrame."""
        import umap as umap_lib

        emb_path = Path(self.cfg.inputs.embedding_npz)
        data = np.load(emb_path, allow_pickle=True)
        mu = data["mu"]
        pdb_paths = data["pdb_paths"].tolist()
        a3m_paths = data["a3m_paths"].tolist()
        is_reference = data["is_reference"]
        ref_labels = data["ref_label"].tolist()

        if not np.all(np.isfinite(mu)):
            raise WorkflowError("Embedding contains non-finite values")

        current_hash = embedding_sha256(emb_path)
        model_path = self.umap_dir / "umap_model.joblib"
        inputs_path = self.umap_dir / "umap_inputs.json"

        # joblib is the standard serialization for scikit-learn/UMAP models;
        # the file is generated by this pipeline, not from untrusted sources.
        reducer = None
        if model_path.exists() and not refit:
            cached = json.loads(inputs_path.read_text()) if inputs_path.exists() else {}
            if cached.get("sha256") != current_hash:
                raise WorkflowError(
                    "Embedding has changed since last UMAP fit. "
                    "Pass --refit-umap to recompute."
                )
            logger.info("Loading cached UMAP model")
            reducer = joblib.load(model_path)
            coords_2d = reducer.transform(mu)
        else:
            ucfg = self.cfg.umap
            reducer = umap_lib.UMAP(
                n_neighbors=ucfg.n_neighbors,
                min_dist=ucfg.min_dist,
                n_components=ucfg.n_components,
                metric=ucfg.metric,
                random_state=self.cfg.general.random_seed,
            )
            logger.info("Fitting UMAP...")
            coords_2d = reducer.fit_transform(mu)
            joblib.dump(reducer, model_path)
            logger.info(f"UMAP model saved to {model_path}")

        inputs_path.write_text(json.dumps({"sha256": current_hash, "n_rows": len(mu)}))

        config_used = {
            "n_neighbors": self.cfg.umap.n_neighbors,
            "min_dist": self.cfg.umap.min_dist,
            "n_components": self.cfg.umap.n_components,
            "metric": self.cfg.umap.metric,
        }
        (self.umap_dir / "umap_config_used.json").write_text(
            json.dumps(config_used, indent=2)
        )

        df = pd.DataFrame({
            "pdb_path": pdb_paths,
            "a3m_path": a3m_paths,
            "UMAP1": coords_2d[:, 0],
            "UMAP2": coords_2d[:, 1],
            "is_reference": is_reference,
            "ref_label": ref_labels,
        })
        return df

    def assign_bins(self, df: pd.DataFrame) -> pd.DataFrame:
        """Assign 2D grid bins and persist grid.json + CSV."""
        ucfg = self.cfg.umap
        bs = self.cfg.binning.bin_size

        if ucfg.umap1_range is not None:
            u1_min, u1_max = ucfg.umap1_range
        else:
            u1_min = float(np.floor(df["UMAP1"].min()))
            u1_max = float(np.ceil(df["UMAP1"].max()))

        if ucfg.umap2_range is not None:
            u2_min, u2_max = ucfg.umap2_range
        else:
            u2_min = float(np.floor(df["UMAP2"].min()))
            u2_max = float(np.ceil(df["UMAP2"].max()))

        grid = {
            "umap1_range": [u1_min, u1_max],
            "umap2_range": [u2_min, u2_max],
            "bin_size": bs,
        }
        (self.umap_dir / "grid.json").write_text(json.dumps(grid, indent=2))

        df = df.copy()
        df["bin_ix"] = np.floor((df["UMAP1"] - u1_min) / bs).astype(int)
        df["bin_iy"] = np.floor((df["UMAP2"] - u2_min) / bs).astype(int)

        in_range = (
            (df["UMAP1"] >= u1_min) & (df["UMAP1"] <= u1_max)
            & (df["UMAP2"] >= u2_min) & (df["UMAP2"] <= u2_max)
        )

        refs_oor = df[df["is_reference"] & ~in_range]
        if len(refs_oor) > 0:
            raise WorkflowError(
                f"Reference structures out of UMAP range: "
                f"{refs_oor['ref_label'].tolist()}"
            )

        oor = df[~df["is_reference"] & ~in_range]
        if len(oor) > 0:
            oor.to_csv(self.umap_dir / "out_of_range.csv", index=False)
            logger.warning(f"{len(oor)} sampling points out of range (saved to out_of_range.csv)")
            df = df[in_range].reset_index(drop=True)

        df.to_csv(self.umap_dir / "umap_coords.csv", index=False)
        logger.info(f"Assigned bins: {len(df)} points, grid [{u1_min},{u1_max}]x[{u2_min},{u2_max}], bin_size={bs}")
        return df

    # ------------------------------------------------------------------
    # Diagnostic UMAP plots (project stage)
    # ------------------------------------------------------------------

    def compute_sampling_rmsds(
        self, df: pd.DataFrame, n_jobs: int = 32
    ) -> pd.DataFrame:
        """Compute RMSD of every sampling structure vs each reference.

        Returns the input *df* with extra columns ``rmsd_{ref_label}`` for
        each reference.  Uses joblib Parallel with *n_jobs* workers.
        """
        from joblib import Parallel, delayed
        from af_claseq.utils.structure_analysis import StructureAnalyzer

        sa_cfg = self.cfg.structure_analysis
        if sa_cfg is None:
            logger.warning("No structure_analysis config — skipping RMSD computation")
            return df

        sa_json_path = sa_cfg.config_json
        with open(sa_json_path) as f:
            sa_json = json.load(f)

        refs_df = pd.read_csv(self.cfg.inputs.references_csv)

        from .coords import _parse_index_spec

        df = df.copy()

        for crit in sa_json.get("filter_criteria", []):
            sup_idx = _parse_index_spec(crit["superposition_indices"])
            rmsd_idx = _parse_index_spec(crit["rmsd_indices"])
            ref_pdb = crit["ref_pdb"]
            col_name = crit["name"]

            ref_label = None
            for _, rrow in refs_df.iterrows():
                if rrow["ref_pdb"] == ref_pdb or col_name.startswith(rrow["ref_label"]):
                    ref_label = rrow["ref_label"]
                    break

            if ref_label is None:
                continue

            rmsd_col = f"rmsd_{ref_label}"
            logger.info(f"Computing {rmsd_col} for {len(df)} structures ({n_jobs} workers)...")

            def _compute_one(pdb_path, is_ref):
                if is_ref:
                    return float("nan")
                try:
                    sa = StructureAnalyzer()
                    return sa.calculate_ca_rmsd(
                        reference_pdb=ref_pdb,
                        target_pdb=pdb_path,
                        superposition_indices=sup_idx,
                        rmsd_indices=rmsd_idx,
                        chain_id="A",
                    )
                except Exception:
                    return float("nan")

            rmsds = Parallel(n_jobs=n_jobs)(
                delayed(_compute_one)(row["pdb_path"], row["is_reference"])
                for _, row in df.iterrows()
            )
            df[rmsd_col] = rmsds

        csv_path = self.umap_dir / "umap_rmsd_vs_refs.csv"
        df.to_csv(csv_path, index=False)
        logger.info(f"Saved RMSD values to {csv_path}")
        return df

    def plot_umap_diagnostic(self, df: pd.DataFrame) -> List[Path]:
        """Generate UMAP scatter plots colored by RMSD to each ref."""
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        plots: List[Path] = []
        plot_cfg = self.cfg.plotting
        colors_map = plot_cfg.colors

        refs_df = df[df["is_reference"]]

        rmsd_cols = [c for c in df.columns if c.startswith("rmsd_")]
        for rmsd_col in rmsd_cols:
            ref_label = rmsd_col.replace("rmsd_", "")
            sampling = df[~df["is_reference"]].dropna(subset=[rmsd_col])
            if sampling.empty:
                continue

            fig, ax = plt.subplots(figsize=(8, 7))
            sc = ax.scatter(
                sampling["UMAP1"], sampling["UMAP2"],
                c=sampling[rmsd_col], cmap="coolwarm", s=4, alpha=0.6,
                vmin=0,
            )
            plt.colorbar(sc, ax=ax, label=f"RMSD to {ref_label} (A)")

            for _, rr in refs_df.iterrows():
                color = colors_map.get(rr["ref_label"], "black")
                ax.scatter(rr["UMAP1"], rr["UMAP2"], c=color,
                           marker="*", s=200, edgecolors="black", linewidths=0.8,
                           zorder=10, label=rr["ref_label"])

            ax.set_xlabel("UMAP1")
            ax.set_ylabel("UMAP2")
            ax.set_title(f"UMAP colored by RMSD to {ref_label}")
            ax.legend(loc="best")
            plt.tight_layout()

            for fmt in plot_cfg.formats:
                p = self.umap_dir / f"umap_rmsd_{ref_label}.{fmt}"
                fig.savefig(p, dpi=300, bbox_inches="tight")
                plots.append(p)
            plt.close(fig)

        logger.info(f"Generated {len(plots)} UMAP diagnostic plots")
        return plots
