"""Full VAE training pipeline test on synthetic data."""

import json
import pytest
import numpy as np
import yaml
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture
def vae_config_path(tmp_path):
    """Create a minimal VAE config pointing to synthetic fixtures."""
    syn_dir = FIXTURE_DIR / "synthetic"
    a3m_dir = FIXTURE_DIR / "a3ms"

    structs_csv = tmp_path / "structures.csv"
    with open(structs_csv, "w") as f:
        f.write("pdb_path,a3m_path\n")
        for i in range(20):
            pdb = syn_dir / f"sample_{i:02d}.pdb"
            a3m = a3m_dir / f"group_{i % 10:02d}.a3m"
            f.write(f"{pdb},{a3m}\n")

    refs_csv = tmp_path / "references.csv"
    with open(refs_csv, "w") as f:
        f.write("ref_pdb,ref_label,ref_chain\n")
        f.write(f"{syn_dir / 'ref_A.pdb'},ref_A,A\n")
        f.write(f"{syn_dir / 'ref_B.pdb'},ref_B,A\n")

    sa_json = tmp_path / "sa.json"
    json.dump({
        "basics": {"full_index": {"start": 1, "end": 15}},
        "filter_criteria": [],
    }, open(sa_json, "w"))

    out_dir = tmp_path / "output"
    cfg = {
        "general": {"protein_name": "TEST", "base_dir": str(out_dir), "device": "cpu"},
        "inputs": {
            "structures_csv": str(structs_csv),
            "references_csv": str(refs_csv),
        },
        "structure_analysis": {
            "config_json": str(sa_json),
            "coord_target": "global",
        },
        "coord_extraction": {
            "alignment_ref_pdb": str(syn_dir / "ref_A.pdb"),
            "alignment_ref_chain": "A",
            "target_chain": "A",
            "min_superposition_atoms": 3,
        },
        "vae": {
            "model": {"latent_dim": 4, "hidden_channels": [16], "use_residual": False},
            "training": {
                "epochs": 10,
                "batch_size": 8,
                "learning_rate": 1e-3,
                "kl_weight": 0.05,
                "val_split": 0.2,
                "early_stopping_patience": 100,
                "normalization_mode": "global",
            },
        },
    }
    cfg_path = tmp_path / "vae.yaml"
    cfg_path.write_text(yaml.dump(cfg))
    return cfg_path


class TestVaeTrainingPipeline:
    def test_full_pipeline(self, vae_config_path, tmp_path):
        from af_claseq.umap_voting.config import VaeTrainConfig
        from af_claseq.umap_voting.vae.train import VaeTrainer

        config = VaeTrainConfig.from_yaml(vae_config_path)
        trainer = VaeTrainer(config)
        emb_path = trainer.train()

        assert emb_path.exists()
        # np.load with allow_pickle is needed for object arrays (pdb_paths, etc.)
        # These files are generated by this pipeline, not from untrusted sources.
        data = np.load(emb_path, allow_pickle=True)
        assert "mu" in data
        assert "pdb_paths" in data
        assert "is_reference" in data
        assert data["mu"].shape[1] == 4  # latent_dim
        assert data["is_reference"].sum() == 2  # two refs

        norm_path = config.get_vae_dir() / "normalization_params.npz"
        assert norm_path.exists()
        norm = np.load(norm_path, allow_pickle=True)
        assert str(norm["mode"]) == "global"
        assert norm["mean"].shape == (3,)
